### ISSUE TITLE
BUG rainfall

### ISSUE THREAD

**Issue by neomanu16** [ktrue/CU-HWS#105]
HI KEN, I'm doing a screenshot of the rains I always worry is multiplied by 10 actually weird

![FireShot Capture 064 - Station Météo de   Vars, CH, FR - www meteo16-vars com](https://user-images.githubusercontent.com/47469020/58384902-0d5fcb00-7fe9-11e9-9e60-f4b9c861c218.png)

**Comment by ktrue** [comment]
I think this is now fixed in #107 which now assumes the JSON rain measurements are in mm instead of the prior CM values.
