### ISSUE TITLE
Graphique

### ISSUE THREAD

**Issue by neomanu16** [ktrue/CU-HWS#110]
HI, 

there are always worries with WU
graphics often have problems,
as they are stuck since at 4am ...
BestRegards,
![FireShot Capture 077 - Station Météo de   Vars, CH, FR - www meteo16-vars com](https://user-images.githubusercontent.com/47469020/67148138-2a4cb180-f29c-11e9-8dae-f853bd8ddcef.png)

**Comment by ktrue** [comment]
I think I fixed this issue with the latest commit (updated jsondata/wuupdate.php) to use a different URL for the today data from WU/TWC .. also enabled decimal precision in the returned data.

**Comment by neomanu16** [comment]
HI c'est bon sa marche, Ken pas d'idée pour faire comme brian un graphique annuelle voir avec records...
ça serait top ya que sa qui manque sur notre version Cumulus..

**Comment by ktrue** [comment]
Unfortunately, the WU/TWC API does not offer a Year call, only a Month call (max of 30 days data), unlike the old WU API.  It's a bit complicated to have the year's data fetched automatically, cached by month, then rolled-up into a 'this year' return for the graph.  It's the reason I omitted it from the CU-HWS when the old WU API was discontinued.   So, for now, we have graph data that can be presented with one API call for 'today' and one API call for 'this month', and the graphs reflect that.
