### ISSUE TITLE
Dark Sky Forecast shows snow in centimeters vs inches in non-metric setting

### ISSUE THREAD

**Issue by iannace** [ktrue/CU-HWS#111]
I noticed when Dark Sky Forecast is set for non-metric forecast snow amounts are indicated in centimeters rather than the expected inches. Other items such as temperature, wind speed and rainfall work as expected.

**Comment by ktrue** [comment]
I think that's an API issue.  The forecastds.php script in the template does no conversion of the value.. only displays it.  Their API docs at https://darksky.net/dev/docs state
```
precipAccumulation optional, only on hourly,currently and daily
The amount of snowfall accumulation expected to occur (over the hour or day, respectively), in inches. (If no snowfall is expected, this property will not be defined.)
```
