### ISSUE TITLE
Flag of Switzerland

### ISSUE THREAD

**Issue by Sima73** [ktrue/CU-HWS#112]
Hello! I come from French-speaking Switzerland, so I use the language fr. I wish I could use the flag of Switzerland. That would be cool. Please take note of my request. And thank you for the good job !
Sylvie
[ch.zip](https://github.com/ktrue/CU-HWS/files/4528726/ch.zip)

**Comment by ktrue** [comment]
Sorry for the delay in replying.  I was doing additions to the template to support Aerisweather (English only) forecasts.   The 2020-05 version now has a Swiss flag for you (ch.svg) available as a setup selection in easyweathersetup.php
