### ISSUE TITLE
New wunderground API => weather.com

### ISSUE THREAD

**Issue by MatsA** [ktrue/CU-HWS#14]
Hi ! 
Don't know if You seen the new documentation on the coming API
https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit
(Funny IBM is using Google docs)
The worst thing is that You just get 7 days of History....
Do You and Brian had any discussions about this ? The SQL solution is pretty complex for "simple" users.
The API community thread https://apicommunity.wunderground.com/weatherapi/topics/weather-underground-api-update.
/Mats

**Comment by ktrue** [comment]
Hi Mats,
Brian and I haven't discussed it per se, but I've been well aware of what IBM has been doing with the shutdown of the WeatherUnderground API and the announced replacement with a Weather Channel API.
Brian's graphs don't use the current WU API for data, but rely on the CSV downloads from a query to the Wunderground PWS page like ```https://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID={PWSID}&day={day}&month={month}&year={year}&graphspan=day&format=1```
which returns data like ```Time,TemperatureF,DewpointF,PressureIn,WindDirection,WindDirectionDegrees,WindSpeedMPH,WindSpeedGustMPH,Humidity,HourlyPrecipIn,Conditions,Clouds,dailyrainin,SolarRadiationWatts/m^2,SoftwareType,DateUTC
2019-01-17 00:04:53,55.6,52.4,29.84,SW,224,1.8,5.0,89,0.00,RA,,0.00,0.00,WeatherDisplay:10.37,2019-01-17 08:04:53,
2019-01-17 00:09:48,55.4,52.5,29.84,SSE,155,0.3,3.5,90,0.00,RA,,0.00,0.00,WeatherDisplay:10.37,2019-01-17 08:09:48,
2019-01-17 00:14:48,55.3,52.7,29.85,SSW,210,2.1,4.6,91,0.00,RA,,0.00,0.00,WeatherDisplay:10.37,2019-01-17 08:14:48,
2019-01-17 00:19:46,55.0,52.7,29.85,South,186,0.0,0.0,92,0.00,OVC,,0.00,0.00,WeatherDisplay:10.37,2019-01-17 08:19:46,
...
```
If that page continues to be available, then no changes are needed as it doesn't use the API.  If that page disappears, then the data fetching from the new WU API will have to be done (but will only work if the station is submitting data to WU).
I've been participating in the discussions on the API thread and in direct contact with Victoria at IBM.
So far, only the docs have been released.  No timeframe on when API keys will be available and the announced shutoff date of 15-Feb-2019 is rapidly approaching.  I think there will be another reschedule of the shutoff date as they (IBM) aren't ready to issue API keys so we developers can adapt our code.  For me, it would be the forecast only (to allow WU-forecast.php script to continue).
That's what I know...

**Comment by MatsA** [comment]
OK, thanks for the info. We report to WU via Davis so we are submitting data. For the moment the history files can be downloaded from the WU site in the same layout as You described above. 
Isn't the forecast from DarkSky ? /Mats

**Comment by ktrue** [comment]
Yes, Brian's template only uses DarkSky for forecasts.
My [Saratoga template](https://saratoga-weather.org/wxtemplates/)  used Wunderground for the World forecasts, but switched to DarkSky last year when the WU-forecast.php script was threatened with WU API closure with no replacement available.  I'll likely rewrite that script for the new API (and am not happy about only a 5 day forecast) but keep the Saratoga World template using DarkSky as shipped.
Brian's template will remain using DarkSky for forecasts.

**Comment by ktrue** [comment]
Had a note from Victoria at IBM/WU
```
We'd like to remind our PWS owners/contributors:

    Your past data will always be available to you for viewing and download in a web browser on wunderground.com, just like it always has. 

    If you are in the small minority of people who use the WU API and a corresponding WU API key to obtain data in .json format, here's what's happening:

- We'll open a registration page for you to get a new API key to get your data in .json format
- You'll sign up and get a new API key for the new API
- Once the registrati on page is open, we'll keep the old API and your old API key active for 2 weeks to allow transition time to your new key
 
We'll announce in the forum when the registration page opens.
Or, email victoria.gardner@ibm.com to receive an email notification once it's ready.
 

    The new API will provide access to 
    Current observations from the PWS netwo rk
    5 day daily forecast
    PWS historical data
    PWS lookup by geocode, zip code and location
    Call volume: 1500/day, 30/minute

The documentation for the new API is available [here.](https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit)

Victoria Gardner
```
It's the "Your past data will always be available to you for viewing and download in a web browser on wunderground.com, just like it always has. " statement that gives me a bit of joy.. the current WU data fetch is via that very mechanism and returns a CSV file.  (Same as used by the wxwuhistory.php script in my Saratoga template set).  We may not have to fiddle with API use for that graphing data at all...

**Comment by MatsA** [comment]
Thanks for the info. Then we hope for the best, no change for history data/Mats

**Comment by ktrue** [comment]
Ok.. added forecast3wu.php and outlookwu.php (along with a bunch of extra language support things) to #80 -- be sure to run easyweathersetup.php after you git pull -- otherwise the menu will appear wonky.
easyweathersetup has a setting for your WU/TWC API key, and a selection box for using DarkSky or Wunderground for your forecasts.

**Comment by MatsA** [comment]
Very nice update !

**Comment by MatsA** [comment]
Hi Ken.

Very nice update and great work !! Works very well !!


Did a check and added my WeatherLink update program to ”windspeeddirection.php” and it seems that it is executed every 17 second ?? So added some code to restrict it to run maximum once every minute.


And a minor issue… If You have 2 warnings in the notification info box it will not show both in a nice way. Se enclosed picture where it is both a freeze and strong wind warning.


Best Regards
Mats



Mats Ahlklo +46 76 20 99 200
mats.ahlklo@icloud.com
