### ISSUE TITLE
Really nice You have taken care of the Cumulus version of Weather34 !!

### ISSUE THREAD

**Issue by MatsA** [ktrue/CU-HWS#2]
Have done some PR:s and have some more issues which I can’t really handle …
1/ Had some problem with translated text from language files and then discovered that in every lang.xx.php There are 2, two,  positions of ”$lang['Windspeed’]” ?? 
2/ Changing language doesn’t work as it used to. Just some headings are changing compared to the old codebase we use in http://vader.domsten.nu
3/ sun1.php and sun2.php have hardcoded text instead of using $lang[xx]. I tried to change but couldn’t handle it. Some tip ?
/Mats

**Comment by MatsA** [comment]
Hi, 
did a second try, with sun1/2 and think I solved the $lang[xxx] thing, but if there are other issues I will not do any updates. Please note that  "hrs" at Daylight/Darkness, "Azimuth" and "Elevation" don't have any keys to the lang files.

**Comment by ktrue** [comment]
The issue with the original sun3.php (from sun_block.php by Wim) was an arc() of zero radians was specified to draw the sun blip on the 24hr dial.  Some browsers (Chrome) drew the blip, other's did not.
I fixed sun3.php to draw an actual 6px radius full circle at the position instead.
