### ISSUE TITLE
Darksky and metar updates

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#25]
Ken,
Getting multiple issues of darksky and metar stalling on updates. Unsure why as many including mine working fine. Have eliminated permissions / groups / user being the cause

**Comment by ktrue** [comment]
Take a look at the jsondata/darksky.txt to see what it says.
I noticed an issue with both on one of my test sites, but a page reload brought both back online.

**Comment by steepleian** [comment]
I think the issue that users are finding is that there are no updates from the get go. They are just stuck with the demo data in the jasondata folder. There seems to be no obvious cause from the code point of view. I am just wondering whether there is an issue when making api calls from a particular location. This has happened with one user with metar but was solved when changing location settings.

**Comment by ktrue** [comment]
The contents of the JSON file would indicate if someone had specified an invalid key or invalid lat/long.  The jsondata/wuupdate.php script is responsible for fetching new data from the various sources .. It's executes 
```
<?php
if(file_exists('darksky.txt')&&time()- filemtime('darksky.txt')>3600){
// weather34 darksky  curl based
$url4 = 'https://api.forecast.io/forecast/'.$apikey.'/'.$lat.','.$lon.'?lang='.$language.'&units='.$darkskyunit ;
$ch4 = curl_init($url4);
$filename4 = 'darksky.txt';
$complete_save_loc4 = $filename4; 
$fp4 = fopen($complete_save_loc4, 'wb'); 
curl_setopt($ch4, CURLOPT_FILE, $fp4);
curl_setopt($ch4, CURLOPT_HEADER, 0);
curl_exec($ch4);
curl_close($ch4);
fclose($fp4);}?>
```
so if the jsondata/darksky.txt file is writable, it should receive the results of the last fetch (just not the return headers from the REST query).  If the file is writable AND just contains old data, the curl request may have aborted..  Time for them to check the Apache error_log to see if errors were posted there.

I think I may rewrite the wuupdate.php to have additional diagnostics (and handle the errors with a bit more finesse)

**Comment by steepleian** [comment]
Ok I will ask them to check the Apache error logs. Will have to buff up on that myself, but not a problem. Will let you know if anything turns up.

Have something else to discuss. Not an issue more an opportunity. Will pm you via Cumulus forum when I am back home.

**Comment by ktrue** [comment]
I'm going to mark as a 'Bug' and continue with the debugging.

**Comment by steepleian** [comment]
Have now established with every single weeWX version user who flagged this up that the issue was 'self' inflicted. Users deleted all files (apart from wuupdate.php) from the jasondata folder because I quote 'it was somebody else's old data'. Once the folder was restored containing all the files, updating of Darksky forecasts and local Metar conditions proceeded as expected. There also appeared to be confusion with some users in that they thought it was either or Darksky api and metar api rather than both.

**Comment by ktrue** [comment]
For new users (freshly cloned), I've added some fixes to create an initial settings1.php since that file was excluded from distribution by the .gitignore spec to avoid clobbering an existing setup when a git pull does updates.

A new initial-settings1.php with nominal settings will be copied to settings1.php if settings1.php doesn't exist by both index.php and easyweathersetup.php.

Hopefully, this new method will ease the initial setup for folks.

Also.. the jsondata/wuupdate.php was revised to fetch new data if the cache file has expired OR it doesn't exist.
