### ISSUE TITLE
airqualitymodule.php not showing color circle on all browsers

### ISSUE THREAD

**Issue by ktrue** [ktrue/CU-HWS#26]
On some browsers, the color circle behind the face image does not show.
Looking at the HTML generated shows HTML errors (unclosed <img>) that when closed with a /> screws up all the formatting for the module.
Looks like HTML relies on quirks-mode to render.  Needs to be massaged to produce proper HTML.

**Comment by weather34** [comment]
hi ken quick fix just grab the airqualitymodule.php from the mb version . probably cu version is looking for some undefined css . i dropped in everything was fine through 0 to 500+ 
![kt](https://user-images.githubusercontent.com/20555738/51968327-bacf3180-2482-11e9-9baf-a530db5ec04c.png)

**Comment by ktrue** [comment]
I've merged airqualitymodule.php and purpleair.php from the Meteobridge distribution.  airqualitymodule has some internationalization, purpleair.php is English only at present.
Closing this issue for now.
