### ISSUE TITLE
Latest updates

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#30]
Ken,

Re-forked your master this morning to capture all your updates. There seems to be a problem. See screenshot.
![screenshot 1](https://user-images.githubusercontent.com/18438654/52122655-92c70600-261b-11e9-98d7-8f3d58d5dcd9.png)

I then tried a download zip from your master several times. The same thing happened. I have seen this happen before which was caused by a CSS problem.

Ian

**Comment by MatsA** [comment]
Hi! Have You reused an old settings1.php from a former installation? Test with the original. 
Think there was something with homeindoor.php. Are You referensing this via settings ? Use some other app testning./Mats

**Comment by MatsA** [comment]
Just did a download with `sudo git clone https://github.com/ktrue/CU-HWS.git` on a Mac which worked OK. /Mats

**Comment by steepleian** [comment]
No I did not use old settings. It was a clean install on my test server.

**Comment by ktrue** [comment]
Well Dang Me!
I forgot to test an initial download first setup scenario from the master, and now I have and replicated the issue.  I'd previously added an entry in .gitignore for settings1.php (main configuration) so as not to clobber any existing installation when they did a git pull to update.  That also meant that a clone/download of the master would not include settings1.php, and that broke just about everything.
Sorry...
So.. I created initial-settings1.php with my default settings (minus the two API keys) and updated index.php and easyweathersetup.php to check for existence of settings1.php and if not found, copy initial-settings1.php to settings1.php so either the index or easyweathersetup would work.
Also updated jsondata/wuupdate.php to do the update if a cache file doesn't exist.
That should fix the initial install issues.

**Comment by ktrue** [comment]
I just tried this update with a clean install and it worked (my sample data, no api keys, no password) for easyweathersetup or index first load.

n.b. I also did a git rm for a bunch of cache files in chartswudata/*2018.txt to remove old data caches.

**Comment by MatsA** [comment]
Nice update ! The "translated" forecast works fine except for `snow` ? Maybe in the info from DarkSky ? 

![w34_forecast](https://user-images.githubusercontent.com/16189982/52137970-2ca6a700-264c-11e9-8caf-07196cf0b91b.png)

Just sent an message with my private adress from Your site using `Contact us`. Maybe it sometimes is more simple to have a dialog that way then via an issue ? Just ping me with a mail./Mats

**Comment by steepleian** [comment]
Working here as well thanks Ken

**Comment by ktrue** [comment]
Ian, thanks for checking!

Mats, the 'snow' translation isn't in the existing languages/lang.LL.php files, but $lang['Rain'] = 'Regn';
was in all the files.  So (lazy me), I decided to use the Rain translation, but ignore the Snow one for now.
As the language translations get reworked, I'll make sure a Snow entry exists and update the DarkSky forecasts/conditions files then.
Yes, got your message via email.. it's ok to continue with issues here if you like - that way Ian can see them too.  Direct correspondence is also welcome to my email :)

**Comment by ktrue** [comment]
Closing this as the original bug was fixed by the update.  I'll have the 'Snow' translation with the update to the language architecture.
