### ISSUE TITLE
Floating weather34 icon in footer

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#33]
the right hand icon on the HWS footer defaults to the weather34 icon if Davis or Weatherflow are not selected in settings. It is floating and overlapping into the pop-up link bar of the bottom right module.

example at https://claydonsweather.org.uk/CU-HWS

**Comment by ktrue** [comment]
Oooh.. subtle issue.  I adjusted both CSS and the index.php to display the hardware logos correctly.
Fixed in [#34](https://github.com/ktrue/CU-HWS/pull/34) merge to master.

Thanks for spotting it Ian!

**Comment by steepleian** [comment]
Perfect
