### ISSUE TITLE
diags.php is a good add on.

### ISSUE THREAD

**Issue by MatsA** [ktrue/CU-HWS#4]
Hi ! Had I guy today, [reading my blogpost](https://pysselilivet.blogspot.com/2017/01/install-weather34-with-weatherlink.html), who was missing the "mbstring" package. Maybe this should be added as a test ? /Mats

**Comment by ktrue** [comment]
The only file in the template that was using mb_ functions was common.php -- I don't think we need to do those settings anymore, so I'm commenting out those in common.php.

Glad you like the diags.php -- doing remote support for users without having that info is a real bear :)

**Comment by MatsA** [comment]
Good solution. One less thing......
