### ISSUE TITLE
outlookds bug 

### ISSUE THREAD

**Issue by neomanu16** [ktrue/CU-HWS#46]
HI kent, there is a bug on the statistics there is that% for precipitation there is no digit.
Best regards,
![fireshot capture 35 - station meteo de vars ch fr - http___meteo-vars fr_index php](https://user-images.githubusercontent.com/47469020/52516665-691b6980-2c2f-11e9-8c36-28a7b8ea77a0.png)

**Comment by weather34** [comment]
looks like $darkskydayPrecipProb = $cond['precipProbability']*100; is missing 


        foreach ($darkskydayCond as $cond) {
            $darkskydayTime = $cond['time'];
            $darkskydaySummary = $cond['summary'];
            $darkskydayIcon = $cond['icon'];
            $darkskydayTempHigh = round($cond['temperatureMax']);
            $darkskydayTempLow = round($cond['temperatureMin']);
			$darkskydayWinddir = $cond['windBearing'];
			$darkskydayClouds = $cond['cloudCover']*100;
            $darkskydayHumidity = $cond['humidity']*100;
			$darkskydayUV = $cond['uvIndex'];
			**$darkskydayPrecipProb = $cond['precipProbability']*100;**
			
            if (isset($cond['precipType'])){

**Comment by neomanu16** [comment]
Thanks it was good ..

**Comment by ktrue** [comment]
Thanks to you both!  I've updated outlookds.php (Merge #47 ) with the corrected code.  Now the PoP displays on the daily forecast detail display.
