### ISSUE TITLE
heat index notification

### ISSUE THREAD

**Issue by weather34** [ktrue/CU-HWS#5]
in barometer.php the notifications are here at the foot of page

the anyToC( should be placed before the $weather["heat_index"]

change
**if(anyToC($notifications=='yes' && $weather["heat_index"])>=30)**{?><div id="weather34lightningdialog-notify">  <div class="weather34lightningdialog-box">

to

**if($notifications=='yes' && anyToC($weather["heat_index"])>=30)**{?><div id="weather34lightningdialog-notify">  <div class="weather34lightningdialog-box">

**Comment by ktrue** [comment]
Thanks, Brian.  I found and made that correction in the master.

Best regards,
Ken
