### ISSUE TITLE
Bug Métar

### ISSUE THREAD

**Issue by neomanu16** [ktrue/CU-HWS#58]
HI Ken,

I just found a little bug on the metar file

Best regards,

Emmanuel

![fireshot capture 47 - station meteo de vars ch fr - http___www meteo16-vars com_](https://user-images.githubusercontent.com/47469020/53360800-d4a34d80-3936-11e9-87b5-f41b25720d17.png)

**Comment by ktrue** [comment]
Hi Emmanuel,
What is the URL to your HWS website.. I'll take a look, and thanks for spotting the error.

**Comment by neomanu16** [comment]
http://www.meteo16-vars.com/

**Comment by weather34** [comment]
checkwx change humidity api to string last week

file metar34get.php


$metar34humidity          = $parsed_json->{'data'}[0]->{'humidity_percent'};

to

$metar34humidity          = $parsed_json->{'data'}[0]->{'humidity'}->{'percent'};

**Comment by neomanu16** [comment]
Thanks Brian 
it's good it works well now

**Comment by ktrue** [comment]
Yes, thanks Brian.
I've done merge #59 with this fix.
