### ISSUE TITLE
Proposal to use a new WeeWX svg  icon created by Brian Underdown

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#61]
[icon-weewx.zip](https://github.com/ktrue/CU-HWS/files/2946784/icon-weewx.zip)

The icon works well in the footer with both the dark and light theme.

<img src="img/icon-weewx.svg" alt="WeeWX Weather Software" title="WeeWX Weather Software"  width="150px" height="55px” >

**Comment by ktrue** [comment]
Got it.. and merged it to master.

Thanks for the heads-up, Ian.

**Comment by steepleian** [comment]
Thanks Ken
