### ISSUE TITLE
Barometer module broken with WeeWX realtime.txt

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#84]
Some time yesterday afternoon, the barometer module suddenly corrupted (see attached screenshot). This was only with a 'live' realtime.txt file. On reverting to the demo realtime file the problem corrected. A clean install of the template failed to correct.

CU-HWS has been jogging along for weeks without a problem. There has been no change to the extension that generates the realtime file from WeeWX or indeed WeeWX itself. I have tried for hours  to correct but it has defeated me. 

Screen shot and a 'real' realtime file attached.
![IMG_0003](https://user-images.githubusercontent.com/18438654/55535558-7bee6f80-56af-11e9-8640-d552232471dc.jpg)
[realtime.zip](https://github.com/ktrue/CU-HWS/files/3042084/realtime.zip)

**Comment by weather34** [comment]
hi I an my guess some formula change the realtime.txt has a value 1071.1 in itself so the error comes from weewx

**Comment by weather34** [comment]
clearly see the 1071+ values in the realtime.txt what does the original weewx file generate 

04/04/19 07:46:26 2.2 88 0.4 5.9 4.7 281 0.0 0.0 1071.1 W 1 km/h C mb mm 15.4 -0.5 5.1 5.1 0.3 15.7 51 2.2 2.5 2.1 07:45 -0.9 05:30 6.7 06:55 14.8 06:55 1074.2 00:05 1070.8 07:40 3.9.1 0 14.8 2.2 2.2 0 0.0 71 287 0.0 0 1 0 W 304 m -0.6 1.2 77.4 0

**Comment by steepleian** [comment]
Yes I see it. My current barometer reading is much lower than that. I always wanted to get an entry into the Guinness Book of Records!!! Obviously something is broken in WeeWX and I can see a huge jump on the graph. Thanks Brian, its always good to have a fresh set of eyes to spot the thing that has been staring me in the face all along.
