### ISSUE TITLE
Unable to switch main station clock to 12 hour format

### ISSUE THREAD

**Issue by steepleian** [ktrue/CU-HWS#90]
When selecting 12 in settings (or changing manually), the main station clock remains on 24 hr display format.

**Comment by ktrue** [comment]
Ahh... the original code had only 24hr clock display capability.  I've added detection of the settings1.php $timeFormat to auto-set the display to 24hr/12hr am/pm display.  CSS updated to widen the field for no overflow.

**Comment by steepleian** [comment]
Thanks Ken, perfect
