### ISSUE TITLE
Soucis css

### ISSUE THREAD

**Issue by neomanu16** [ktrue/CU-HWS#93]
HI Ken

I think there is a concern about IE and Edge

when you ask him for the black theme he stays blank

it's since you worked on css.

Bizarre.

Best regards,

Emmanuel

**Comment by ktrue** [comment]
Hi Emmanuel,
Yes, I see there are now issues with the main.dark.css with IE and Edge -- I was trying to clean up validation for the CSS (there were many errata) and apparently, I cleaned up some errata that IE and Edge used for their formatting.  The display of the Dark theme on Firefox, Chrome, Opera and Safari all appear normal with the cleaned-up main.dark.css, just not IE or Edge.  Thanks again, Microsoft, for making variant browsers.  I'll look a what has to be put back to get IE/Edge working again.
Thanks for spotting the issue.

**Comment by ktrue** [comment]
Ok, put back the non-validated main.dark.css (with the clock am/pm fix) with #96 .. I'll try the validation corrections a bit later.  This non-validated css works in Firefox, Chrome, IE, Edge, Opera and Safari.

**Comment by steepleian** [comment]
Never mind, Microsoft are going to move to a Mozilla based browser in the
future.
